language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: pK2F6kY97WMxShk4L8loN6qGiKt89Vi8UJ/sE9C2iHtEBiIdnHaszw9rHjtxxJFjbBcoHCLHmelZGgI12KFEOl8yH7NoOGjm90kNQhHhuB4KZC9Kg8FbBMpJEbrpyYPIsbZ0K3IlMHMR5tPMis5lpyXzPTKHdYJ+VX0OfiZlFFB4rXTUtOr7j2ppsonUpkuE8+ZNIkwi69WDUdb8NWSFgk0BJZrjs6HuKw0mGQu23yy/otyl6kYswkZQl5SxF9AILZ5eu2/VNpbT+oSz41dh6voCNZKVJsmARRzBM8WDot8Fr2WPThTIeKatS33jgWgr+DBW5MUmzM9tPcVAUIL7tqAGWh+mHILDD1gOWwvToIWZj3n+WUpiNJTXoAeu21LRe17An8BdXgHglMsp0chblio5Q00TJCivVsQJKg8AKS95pkrpvdIJiPiwzV5UV1kAJyD4ZA2H2mfcxRl30OTKa0LWggYKxJlF9e1h9rJW1GdDP1sM8CF75IxP/ivJHPB6jzXdpPVBTkH3ThD5vG+xrDm291L7xrQ6e4aRLkhd9WMQgisElsA2hMH2YLkkHUlE559X9vfwWGnjO1ZXvcFqBwL5w9KLxbYNRxjjCABFBqNDZsspP7hK9CbyTRi+ksTvG9AbWDnZHxU3zMtpQ7SfF1D/3d5zbsdUYK0rNNUii+k=
  app: timmy-purdue
skip_cleanup: true
