language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: YUo+rtiX1EDU4lIo6y3rkl1KfvgC4HuBNLLblSlEECxF8wvpygRc54TwgvPsVnvUBZWoMoOqlQzOgloqHn1ig3htj46iF/UR0d6wTvBoSp3TZS9btt1YT6pNHGmMFeyavq+SqFKRuPjrpON5HKvuc7Vcf8/MzFAsCUddw18Cv+nuviVmQGONNac5xOTk8lXrUzl5Hc0tgwUEtGUQ9d+cRuhhGOvX0pN62JttmM+SuLxdRQ5Au+fw8CgOKyG8mqtoPG7cZ6ofuuBFTqJSEKGmv8N2PhRW+918QAkZYG6gRwWlom9Bxri0xeV84Ahwii2SNFNudM/HZYC84TEetzyoczGaCAG8QGA0WqrOruUK7quvYnOnRqtiUuuEwx4t7OpCsGOYmBk/82hpc0aRA50Dd/BFYk1wDpMXcyYc9pcRgc70ld9Cd78SDQPkTyFGMj4AYz9VzOgJi4/sZ7l8cO+0XK8o3YkuwaptwVCt/iYYJFwN/WnrxKgDk+oGBKLFd4yC0DA1r9XR7Eu8zOwk2duWbsx7bgF7ckWwJPS2jjWvzXVN3x04p+1g9kJsQtNTGytEkL05T0sk2y2mhMfIrNHi9EKWij7OFxn01YR2KSZVEJtOfDwrcxqEV7gOmdc6aGXnRALisbMP5cKCWzsHSrinwkCxydSJ605uu4taZ1iQIYM=
  app: timmy-purdue
skip_cleanup: true
